version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tekne
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./dev/data/postgres:/var/lib/postgresql/data
