FROM alpine:3.20

WORKDIR /app

COPY docker-out/meditations meditations
COPY docker-out/build build
COPY docker-out/build public

ADD docker_run_meditations.sh .

CMD /bin/sh docker_run_meditations.sh
