/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CmeditorRouteImport } from './routes/cmeditor'
import { Route as IndexRouteImport } from './routes/index'

const CmeditorRoute = CmeditorRouteImport.update({
  id: '/cmeditor',
  path: '/cmeditor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cmeditor': typeof CmeditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cmeditor': typeof CmeditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cmeditor': typeof CmeditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cmeditor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cmeditor'
  id: '__root__' | '/' | '/cmeditor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CmeditorRoute: typeof CmeditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cmeditor': {
      id: '/cmeditor'
      path: '/cmeditor'
      fullPath: '/cmeditor'
      preLoaderRoute: typeof CmeditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CmeditorRoute: CmeditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
