/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrpcTestRouteImport } from './routes/trpc-test'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NTitleRouteImport } from './routes/n/$title'

const TrpcTestRoute = TrpcTestRouteImport.update({
  id: '/trpc-test',
  path: '/trpc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NTitleRoute = NTitleRouteImport.update({
  id: '/n/$title',
  path: '/n/$title',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/lab': typeof LabRoute
  '/trpc-test': typeof TrpcTestRoute
  '/n/$title': typeof NTitleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/lab': typeof LabRoute
  '/trpc-test': typeof TrpcTestRoute
  '/n/$title': typeof NTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/demo': typeof DemoRoute
  '/lab': typeof LabRoute
  '/trpc-test': typeof TrpcTestRoute
  '/n/$title': typeof NTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/404' | '/demo' | '/lab' | '/trpc-test' | '/n/$title'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/demo' | '/lab' | '/trpc-test' | '/n/$title'
  id: '__root__' | '/' | '/404' | '/demo' | '/lab' | '/trpc-test' | '/n/$title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DemoRoute: typeof DemoRoute
  LabRoute: typeof LabRoute
  TrpcTestRoute: typeof TrpcTestRoute
  NTitleRoute: typeof NTitleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trpc-test': {
      id: '/trpc-test'
      path: '/trpc-test'
      fullPath: '/trpc-test'
      preLoaderRoute: typeof TrpcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$title': {
      id: '/n/$title'
      path: '/n/$title'
      fullPath: '/n/$title'
      preLoaderRoute: typeof NTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DemoRoute: DemoRoute,
  LabRoute: LabRoute,
  TrpcTestRoute: TrpcTestRoute,
  NTitleRoute: NTitleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
